export { default as Home } from './Home.svelte'
export { default as Code } from './Code.svelte'
export { default as Register } from './Register.svelte'
export { default as Terms } from './Terms.svelte'
export { default as Scratch } from './Scratch.svelte'
export { default as Result } from './Result.svelte'
